name: Build
on:
  push:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: ./update.sh
        env:
          CI: true
          ARCHIVE: 1

      - name: Build
        run: ./build.sh
        env:
          TERM: xterm
          ARCHIVE: 1
      
      - name: Set artifact name
        run: |
          git fetch --tags
          echo "ARTIFACT_NAME=progs-$(git describe --tags --dirty='~' --always)" >> $GITHUB_ENV

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            compiled/*
          if-no-files-found: error
          # retention-days: 14

      - name: Publish a release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: |
            compiled/*
